[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/product-list"
  to = "/product-list/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
